// Code generated by MockGen. DO NOT EDIT.
// Source: stat_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Sorrowful-free/short-url-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockStatService is a mock of StatService interface.
type MockStatService struct {
	ctrl     *gomock.Controller
	recorder *MockStatServiceMockRecorder
}

// MockStatServiceMockRecorder is the mock recorder for MockStatService.
type MockStatServiceMockRecorder struct {
	mock *MockStatService
}

// NewMockStatService creates a new mock instance.
func NewMockStatService(ctrl *gomock.Controller) *MockStatService {
	mock := &MockStatService{ctrl: ctrl}
	mock.recorder = &MockStatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatService) EXPECT() *MockStatServiceMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatService) GetStats(ctx context.Context) (model.StatDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(model.StatDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatServiceMockRecorder) GetStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatService)(nil).GetStats), ctx)
}
