// Code generated by MockGen. DO NOT EDIT.
// Source: short_url_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Sorrowful-free/short-url-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockShortURLRepository is a mock of ShortURLRepository interface.
type MockShortURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLRepositoryMockRecorder
}

// MockShortURLRepositoryMockRecorder is the mock recorder for MockShortURLRepository.
type MockShortURLRepositoryMockRecorder struct {
	mock *MockShortURLRepository
}

// NewMockShortURLRepository creates a new mock instance.
func NewMockShortURLRepository(ctrl *gomock.Controller) *MockShortURLRepository {
	mock := &MockShortURLRepository{ctrl: ctrl}
	mock.recorder = &MockShortURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURLRepository) EXPECT() *MockShortURLRepositoryMockRecorder {
	return m.recorder
}

// ContainsUID mocks base method.
func (m *MockShortURLRepository) ContainsUID(ctx context.Context, shortUID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsUID", ctx, shortUID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ContainsUID indicates an expected call of ContainsUID.
func (mr *MockShortURLRepositoryMockRecorder) ContainsUID(ctx, shortUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsUID", reflect.TypeOf((*MockShortURLRepository)(nil).ContainsUID), ctx, shortUID)
}

// DeleteShortURLs mocks base method.
func (m *MockShortURLRepository) DeleteShortURLs(ctx context.Context, userID string, shortURLs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShortURLs", ctx, userID, shortURLs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteShortURLs indicates an expected call of DeleteShortURLs.
func (mr *MockShortURLRepositoryMockRecorder) DeleteShortURLs(ctx, userID, shortURLs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShortURLs", reflect.TypeOf((*MockShortURLRepository)(nil).DeleteShortURLs), ctx, userID, shortURLs)
}

// GetByOriginalURL mocks base method.
func (m *MockShortURLRepository) GetByOriginalURL(ctx context.Context, originalURL string) (model.ShortURLDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOriginalURL", ctx, originalURL)
	ret0, _ := ret[0].(model.ShortURLDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOriginalURL indicates an expected call of GetByOriginalURL.
func (mr *MockShortURLRepositoryMockRecorder) GetByOriginalURL(ctx, originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOriginalURL", reflect.TypeOf((*MockShortURLRepository)(nil).GetByOriginalURL), ctx, originalURL)
}

// GetByUID mocks base method.
func (m *MockShortURLRepository) GetByUID(ctx context.Context, shortUID string) (model.ShortURLDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUID", ctx, shortUID)
	ret0, _ := ret[0].(model.ShortURLDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUID indicates an expected call of GetByUID.
func (mr *MockShortURLRepositoryMockRecorder) GetByUID(ctx, shortUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUID", reflect.TypeOf((*MockShortURLRepository)(nil).GetByUID), ctx, shortUID)
}

// GetUserUrls mocks base method.
func (m *MockShortURLRepository) GetUserUrls(ctx context.Context, userID string) ([]model.ShortURLDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserUrls", ctx, userID)
	ret0, _ := ret[0].([]model.ShortURLDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserUrls indicates an expected call of GetUserUrls.
func (mr *MockShortURLRepositoryMockRecorder) GetUserUrls(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserUrls", reflect.TypeOf((*MockShortURLRepository)(nil).GetUserUrls), ctx, userID)
}

// Ping mocks base method.
func (m *MockShortURLRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockShortURLRepositoryMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockShortURLRepository)(nil).Ping), ctx)
}

// Save mocks base method.
func (m *MockShortURLRepository) Save(ctx context.Context, userID string, shortURL model.ShortURLDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userID, shortURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockShortURLRepositoryMockRecorder) Save(ctx, userID, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockShortURLRepository)(nil).Save), ctx, userID, shortURL)
}

// SaveBatch mocks base method.
func (m *MockShortURLRepository) SaveBatch(ctx context.Context, userID string, shortURLs []model.ShortURLDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, userID, shortURLs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockShortURLRepositoryMockRecorder) SaveBatch(ctx, userID, shortURLs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockShortURLRepository)(nil).SaveBatch), ctx, userID, shortURLs)
}
