// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/short_url_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortURLService is a mock of ShortURLService interface.
type MockShortURLService struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLServiceMockRecorder
}

// MockShortURLServiceMockRecorder is the mock recorder for MockShortURLService.
type MockShortURLServiceMockRecorder struct {
	mock *MockShortURLService
}

// NewMockShortURLService creates a new mock instance.
func NewMockShortURLService(ctrl *gomock.Controller) *MockShortURLService {
	mock := &MockShortURLService{ctrl: ctrl}
	mock.recorder = &MockShortURLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURLService) EXPECT() *MockShortURLServiceMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockShortURLService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockShortURLServiceMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockShortURLService)(nil).Ping), ctx)
}

// TryMakeOriginal mocks base method.
func (m *MockShortURLService) TryMakeOriginal(ctx context.Context, shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryMakeOriginal", ctx, shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryMakeOriginal indicates an expected call of TryMakeOriginal.
func (mr *MockShortURLServiceMockRecorder) TryMakeOriginal(ctx, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryMakeOriginal", reflect.TypeOf((*MockShortURLService)(nil).TryMakeOriginal), ctx, shortURL)
}

// TryMakeShort mocks base method.
func (m *MockShortURLService) TryMakeShort(ctx context.Context, originalURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryMakeShort", ctx, originalURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryMakeShort indicates an expected call of TryMakeShort.
func (mr *MockShortURLServiceMockRecorder) TryMakeShort(ctx, originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryMakeShort", reflect.TypeOf((*MockShortURLService)(nil).TryMakeShort), ctx, originalURL)
}
