// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/short_url_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Sorrowful-free/short-url-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockShortURLRepository is a mock of ShortURLRepository interface.
type MockShortURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLRepositoryMockRecorder
}

// MockShortURLRepositoryMockRecorder is the mock recorder for MockShortURLRepository.
type MockShortURLRepositoryMockRecorder struct {
	mock *MockShortURLRepository
}

// NewMockShortURLRepository creates a new mock instance.
func NewMockShortURLRepository(ctrl *gomock.Controller) *MockShortURLRepository {
	mock := &MockShortURLRepository{ctrl: ctrl}
	mock.recorder = &MockShortURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURLRepository) EXPECT() *MockShortURLRepositoryMockRecorder {
	return m.recorder
}

// ContainsUID mocks base method.
func (m *MockShortURLRepository) ContainsUID(ctx context.Context, shortUID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsUID", ctx, shortUID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ContainsUID indicates an expected call of ContainsUID.
func (mr *MockShortURLRepositoryMockRecorder) ContainsUID(ctx, shortUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsUID", reflect.TypeOf((*MockShortURLRepository)(nil).ContainsUID), ctx, shortUID)
}

// GetByUID mocks base method.
func (m *MockShortURLRepository) GetByUID(ctx context.Context, shortUID string) (model.ShortURLDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUID", ctx, shortUID)
	ret0, _ := ret[0].(model.ShortURLDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUID indicates an expected call of GetByUID.
func (mr *MockShortURLRepositoryMockRecorder) GetByUID(ctx, shortUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUID", reflect.TypeOf((*MockShortURLRepository)(nil).GetByUID), ctx, shortUID)
}

// Ping mocks base method.
func (m *MockShortURLRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockShortURLRepositoryMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockShortURLRepository)(nil).Ping), ctx)
}

// Save mocks base method.
func (m *MockShortURLRepository) Save(ctx context.Context, shortURL model.ShortURLDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, shortURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockShortURLRepositoryMockRecorder) Save(ctx, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockShortURLRepository)(nil).Save), ctx, shortURL)
}
